# Modeled after solana-labs/ecosystem file-lint.yaml workflow
# See https://github.com/solana-labs/ecosystem/blob/master/.github/workflows/file-lint.yaml

name: Validate tag values in project MD files

# This workflow is triggered on PRs to main branch on the repository
on:
  pull_request_target:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        if: ${{ github.event.pull_request.number }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      # This will lint all files, see https://github.com/timhagn/lint-md-fm
      - name: Lint Current PR
        id: lint
        uses: ./.github/actions/lint-fm-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changed-files: ""
          directories: |
            src/content
            public/img/project-images
          markdown-extensions: |
            .md
            .mdx
          image-extensions: |
            .png
            .svg
            .jpg
            .jpeg
