# Modeled after solana-labs/ecosystem file-lint.yaml workflow
# See https://github.com/solana-labs/ecosystem/blob/master/.github/workflows/file-lint.yaml

name: Validate tag values in project MD files

# This workflow is triggered on PRs to main branch on the repository
on:
  pull_request:
  # pull_request_target:
  #   branches: [main, test]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        if: ${{ github.event.pull_request.number }}
        uses: actions/checkout@v4

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.md
            **.mdx
          files_ignore: |
            project-template.md
            tagsList.md
            README.md

      - name: Setup node
        if: steps.changed-markdown-files == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install npm dependencies
        if: steps.changed-markdown-files == 'true'
        uses: bahmutov/npm-install@v1
        with:
          working-directory: .github/actions

      - name: Lint MD frontmatter for changed files
        if: steps.changed-markdown-files == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: node .github/actions/validate-tags.js

      - name: Comment PR with validation report
        if: steps.changed-markdown-files == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: validation-report.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
